### ISSUE TITLE
from model.PaddleOCR2Pytorch.load_svtrnet import load_svtrnet，是个空文件夹请问里面的文件load_svtrnet在哪里可以找到呢

### ISSUE THREAD

**Issue by youwei666** [SijieLiu518/SGENet#1]
from model.PaddleOCR2Pytorch.load_svtrnet import load_svtrnet是个空文件夹请问里面的文件在哪里可以找到呢

**Comment by SijieLiu518** [comment]
你可以在[here](https://github.com/frotms/PaddleOCR2Pytorch.git)找到相关文件和模型权重，load_svtrnet.py 已经推送至[here](https://github.com/SijieLiu518/SGENet/blob/master/model/PaddleOCR2Pytorch/load_svtrnet.py)

**Comment by youwei666** [comment]
> 你可以在[here](https://github.com/frotms/PaddleOCR2Pytorch.git)找到相关文件和模型权重，load_svtrnet.py 已经推送至[here](https://github.com/SijieLiu518/SGENet/blob/master/model/PaddleOCR2Pytorch/load_svtrnet.py)

谢谢！请问是要把整个PaddleOCR2Pytorch都下载之后放到文件里吗？PaddleOCR2Pytorch\pytorchocr\modeling\transforms\tps_spatial_transformer.py这个文件报错是什么问题呢
